### ISSUE TITLE
requirement error: `pypapi` not supported on python3. Replace with `python_papi`

### ISSUE THREAD

**Issue by Ujjawal-K-Panchal** [rohdelab/rcdt_ns_classifier#8]
Hi authors.
First of all, great paper. Thoroughly enjoyed reading.

Many people use `python3` these days, for which, the requirement `pypapi` (mentioned [here](https://github.com/rohdelab/rcdt_ns_classifier/blob/f35d1f3d4c55ecdfeca859e738e9165b4c75a76d/compare_classification_methods/requirements.txt#L11)) doesn't install correctly from the requirements file themselves. This is because, pip redirects the `pypapi` keyword to an older version of the library which used `pysqlite`, which is not supported in `Python3`. Seems they have already upgraded it in the latest release available under the keyword `python_papi`.

So I recommend to replace it [the given line](https://github.com/rohdelab/rcdt_ns_classifier/blob/f35d1f3d4c55ecdfeca859e738e9165b4c75a76d/compare_classification_methods/requirements.txt#L11) with the keyword: `python_papi` which works.

Note, use of `python_papi` is also mentioned in the [official documentation of papi for python](https://flozz.github.io/pypapi/install.html).

Also, since this repo includes a notebook, perhaps putting `jupyter` or individually `jupyter-lab` and `notebook` as [documented here](https://jupyter.org/install) will be useful, to be self contained.
Thanks!

**Comment by xuwangyin** [comment]
Thanks for the comments. We have fixed the issue using the suggested solution.

**Comment by Ujjawal-K-Panchal** [comment]
Thanks!
